### ISSUE TITLE
Spring Rest Docs로 API 문서화

### ISSUE THREAD

**Issue by shkisme** [Pusan21/Elecvery-Clone-Backend#37]
## 사전 수행 이슈

- [x]  CRUD기능 API (내 지불 관리 CRUD API)

## 이슈 내용

`Spring Rest Docs` 사용을 위해, Controller Test 코드를 작성하고,
`Spring Rest Docs` 로 `내 지불 관리 API` 문서화를 진행합니다.

## TODO

- [x] 내 지불 관리 Controller Test 코드 작성
- [x] 내 지불 관리 API 문서화 진행
